module Pages exposing (viewAbout, viewSpeakers, viewCodeOfConduct)

import Html exposing (..)
import Html.Attributes exposing (..)


-- import Model exposing (Page(..))
-- import Svg exposing (defs, g, path, svg)
-- import Svg.Attributes exposing (d, fill, viewBox)


viewAbout : Html a
viewAbout =
    div []
        [ h2 []
            [ text "The Elm Conference With A Nordic Twist" ]
        , h3 []
            [ text "What to expect?" ]
        , p []
            [ text "A full day conference filled with interesting talks and discussions about Elm. You will get to hear a mix of talks from international speakers and experience reports from Norwegian/Nordic users." ]
        , p []
            [ text "By the end of the conference you should hopefully have an answer to the following question: " ]
        , blockquote []
            [ i []
                [ text "When is Elm the right choice?" ]
            ]
        , h3 []
            [ text "Why Elm?" ]
        , p []
            [ text "Elm is a fast-growing programming language for the web that significantly improves development speed, reliability, maintainability and developer experience. With React and Redux’s popularity on the frontend, functional programming practices are going mainstream and many are looking to Elm as the natural next step." ]
        , h3 []
            [ text "Intended audience" ]
        , p []
            [ text "The intended audience for the conference ranges from the curious JavaScript developer to the experienced functional programmer." ]
        , h3 []
            [ text "What is Elm?" ]
        , p []
            [ text "Elm is a functional language that compiles to JavaScript. It competes with projects like React as a tool for creating websites and web apps. Elm has a very strong emphasis on simplicity, ease-of-use, and quality tooling." ]
        , p []
            [ a [ href "http://elm-lang.org/" ]
                [ text "http://elm-lang.org/" ]
            ]
        , h3 []
            [ text "Where?" ]
        , p []
            [ text "The conference will be hosted at the beautiful "
            , em []
                [ text "Gamle Museet" ]
            , text "(The Old Museum) in downtown Oslo."
            ]
        , h3 []
            [ text "Pre-Conference Workshop" ]
        , p []
            [ text "TBA" ]
        , h3 []
            [ text "Tickets" ]
        , p []
            [ a [ href "https://www.eventbrite.co.uk/e/oslo-elm-day-tickets-32813210195" ]
                [ text "Available now!" ]
            ]
        , h3 []
            [ text "Food" ]
        , p []
            [ text "Coffee, tea and fruit will be provided throughout the day. The ticket price includes lunch during the event and dinner at the afterparty. Please contact us if you have any dietary restrictions." ]
        , h3 []
            [ text "Afterparty" ]
        , p []
            [ text "Will be hosted at the venue. We hope to see you there!" ]
        , h3 []
            [ text "Contact us" ]
        , p []
            [ ul []
                [ li []
                    [ a [ href "https://twitter.com/osloelmday" ]
                        [ text "@OsloElmDay" ]
                    ]
                , li []
                    [ a [ href "mailto:hello@osloelmday.no" ]
                        [ text "hello@osloelmday.no" ]
                    ]
                ]
            ]
        , h3 []
            [ text "Who are we?" ]
        , p []
            [ text "The conference is organized by enthusiastic members of the Oslo Elm Meetup community." ]
        , p []
            [ ul []
                [ li []
                    [ text "Erik Wendel – "
                    , a [ href "https://twitter.com/ewndl" ]
                        [ text "@ewndl" ]
                    ]
                , li []
                    [ text "Ingar Almklov – "
                    , a [ href "https://twitter.com/ingara" ]
                        [ text "@ingara" ]
                    ]
                , li []
                    [ text "Kjetil Valle – "
                    , a [ href "https://twitter.com/kjetilvalle" ]
                        [ text "@kjetilvalle" ]
                    ]
                , li []
                    [ text "Erlend Hamberg – "
                    , a [ href "https://twitter.com/ehamberg" ]
                        [ text "@ehamberg" ]
                    ]
                , li []
                    [ text "Magnus Rundberget – "
                    , a [ href "https://twitter.com/mrundberget" ]
                        [ text "@mrundberget" ]
                    ]
                , li []
                    [ text "Noah Hall – "
                    , a [ href "https://twitter.com/eeue56" ]
                        [ text "@eeue56" ]
                    ]
                ]
            ]
        , p []
            [ h3 []
                [ text "With help from" ]
            , ul []
                [ li []
                    [ text "Jonatan Austigard – "
                    , a [ href "https://twitter.com/jonaaust" ]
                        [ text "@jonaaust" ]
                    ]
                , li []
                    [ text "Stian Veum Møllersen – "
                    , a [ href "https://twitter.com/mollerse" ]
                        [ text "@mollerse" ]
                    ]
                ]
            ]
        ]


viewCodeOfConduct : Html a
viewCodeOfConduct =
    div []
        [ h2 []
            [ text "Code of Conduct        " ]
        , text "All delegates, speakers, sponsors and volunteers are required to agree with the following code of conduct. Organizers will enforce this code throughout the event.          "
        , h3 []
            [ text "The Quick Version          " ]
        , p []
            [ text "Our conference is dedicated to providing a harassment-free conference experience for everyone, regardless of gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion (or lack thereof), or technology choices. We do not tolerate harassment of conference participants in any form. Sexual language and imagery is not appropriate for any conference venue, including talks, workshops, parties, Twitter and other online media. Conference participants violating these rules may be sanctioned or expelled from the conference without a refund at the discretion of the conference organisers.          " ]
        , h3 []
            [ text "The Less Quick Version          " ]
        , p []
            [ text "Harassment includes offensive verbal comments related to gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion, technology choices, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention.          " ]
        , p []
            [ text "Participants asked to stop any harassing behavior are expected to comply immediately.          " ]
        , p []
            [ text "Sponsors are also subject to the anti-harassment policy. In particular, sponsors should not use sexualized images, activities, or other material. Booth staff (including volunteers) should not use sexualized clothing/uniforms/costumes, or otherwise create a sexualized environment.          " ]
        , p []
            [ text "If a participant engages in harassing behavior, the conference organizers may take any action they deem appropriate, including warning the offender or expulsion from the conference with no refund.          " ]
        , p []
            [ text "If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact a member of conference staff immediately. Conference staff can be identified by a clearly marked \"STAFF\" shirt.          " ]
        , p []
            [ text "Conference staff will be happy to help participants contact hotel/venue security or local law enforcement, provide escorts, or otherwise assist those experiencing harassment to feel safe for the duration of the conference. We value your attendance.          " ]
        , p []
            [ text "We expect participants to follow these rules at all conference venues and conference-related social events.          " ]
        ]


viewSpeakers : Html a
viewSpeakers =
    div []
        [ h2 []
            [ text "Speakers" ]
        , p []
            [ text "The conference will have one track, with all talks taking place in the same room. We already have three Elm-heroes booked, but there’s room for a lot more! Depending on the amount and duration of talk submissions, we’re aiming for a normal full-length conference day of presentations.          " ]
        , p []
            [ text "There might also be a panel debate or open-space session, in order to provide an arena for discussion or Q&A within the community.          " ]
        , p []
            [ text "Would you like to present something?          Our "
            , a [ href "https://goo.gl/forms/kpQH4DFxdzBXa1oE3", target "_blank" ]
                [ text "call for speakers" ]
            , text "is open until April 21.          "
            ]
        , p []
            [ text "Our current speaker lineup consist of world-renowned Elm experts, experienced with using Elm in production.          " ]
        , article [ class "speaker" ]
            [ img [ class "speaker__image", src "images/richard.jpg" ]
                []
            , div [ class "speaker__content" ]
                [ h3 [ class "speaker__name" ]
                    [ text "Richard Feldman" ]
                , p []
                    [ text "Richard is the author of “Elm in Action” from Manning Publications, and the instructor for the Frontend Masters two-Day Elm Workshop. When he’s not writing about Elm, teaching Elm, speaking about Elm, or co-hosting the San Francisco Elm meetup, he likes to take a break from his job at NoRedInk (where front-end programmers spend almost almost all their coding time writing production Elm code) by kicking back and working on some of his open-source Elm projects.              " ]
                , p []
                    [ text "Some have said he’s “into Elm,” but he’s not sure where they got that wild idea.              " ]
                ]
            ]
        , article [ class "speaker" ]
            [ img [ class "speaker__image", src "images/noah.jpg" ]
                []
            , div [ class "speaker__content" ]
                [ h3 [ class "speaker__name" ]
                    [ text "Noah Hall" ]
                , p []
                    [ text "Noah Hall has been active in the Elm community for over three years, having used Elm in production since version 0.15. He has been a contributor to Elm both in code, ideas, and feedback, and now runs the Elm community Github group as well as the Elm Slack team. He used to work as a researcher focusing on the influence of functional programming on modern web development at university, before he joined NoRedInk as the first hire motivated to join because of Elm. At NRI he focused on tooling, ops, and frontend development. Now he works at Fusetools, but remains very active in the Elm community.              " ]
                ]
            ]
        , article [ class "speaker" ]
            [ img [ class "speaker__image", src "images/luke.jpg" ]
                []
            , div [ class "speaker__content" ]
                [ h3 [ class "speaker__name" ]
                    [ text "Luke Westby" ]
                , p []
                    [ text "Luke Westby is a cofounder and partner at HumbleSpark in Chicago, IL, USA. He is the creator of the browser-based Elm editor Ellie and an active member of the Elm community. He loves contributing to the Elm community by speaking about the language, answering questions in Slack, writing blog posts, and organizing the Chicago Elm Meetup.              " ]
                ]
            ]
        ]
